name: chaty
description: "A firebase chat widget."
version: 1.0.1
homepage: https://github.com/mindsterapps/chaty
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_messaging:
  http:
  flutter_local_notifications:
  firebase_storage:
  image_picker:
  provider:
  permission_handler:
  path_provider:
  firebase_core:
  lints: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: false
