name: chaty
description: "A firebase chat widget."
version: 1.0.0
homepage: https://github.com/aswintbbc/chaty
environment:
  sdk: ^3.4.0
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_messaging:
  http:
  flutter_local_notifications:
  firebase_storage:
  image_picker:
  provider:
  permission_handler:
  path_provider:
  flutter_sound:
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
